[build]
  command = "npm run build"
  publish = ".next"  # Bukan "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/json-server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200